- platform: template
  lights:
    living_room_lights:
      friendly_name: "Living Room Lights"
      unique_id: living_room_template_light
      value_template: "{{ states('light.living_room_ceiling') == 'on' }}"
      turn_on:
        - action: light.turn_on
          data:
            entity_id: light.living_room_ceiling
        # - action: system_log.write
        #   data:
        #     message: "Turn on"
        #     level: error
          # data:
          #   value: 
          #   entity_id: light.living_room_ceiling 
        # - action: input_number.set_value
        #   data:
        #     value: "{{ '%.0f' | format((1000000.0 / color_temp) - 3.0 | float(0)) }}"
        #     entity_id: input_number.living_room_ceiling_color_temp
      turn_off:
        action: light.turn_off
        data:
          entity_id: light.living_room_ceiling
      set_level:
        action: light.turn_on
        data:
          entity_id: light.living_room_ceiling
          brightness: "{{ brightness }}"
      set_temperature:
        - action: input_number.set_value
          data:
            value: "{{ '%.0f' | format((1000000.0 / color_temp) - 3.0 | float(0)) }}"
            entity_id: input_number.living_room_ceiling_color_temp
      set_color:
        - action: light.turn_on
          data_template:
            entity_id: 
              - light.living_room_ceiling
            transition: "{{ transition | float(0) }}"
            hs_color: 
              - "{{ hs[0] }}"
              - "{{ hs[1] }}"
      # set_effect:
      #   - action: light.turn_on
      #     data_template:
      #       entity_id:
      #         - light.living_room_ceiling
      #       effect: "{{ effect }}"
      supports_transition_template: "{{ true }}"