defaults:
  name_prefix: "Soil"
  id_prefix: "soil"
  i2c_bus: bus_a
  i2c_address: "0x36"
  temperature_id: ${id_prefix}_temperature
  temperature_name: "${name_prefix} Temperature"
  moisture_id: ${id_prefix}_moisture
  moisture_name: "${name_prefix} Moisture"
  dry_id: ${id_prefix}_dry
  dry_name: "${name_prefix} Dry"
  dry_threshold: "40"
  dry_hysteresis: "10"
  temperature_offset: "0.0"
  temperature_gain: "1.0"
  temperature_window_size: "5"
  temperature_window_send_every: "5"
  temperature_window_send_first_at: "5"
  moisture_min_value: "350"
  moisture_max_value: "1015"
  update_interval: 2s
  moisture_window_size: "3"
  moisture_window_send_every: "3"
  moisture_window_send_first_at: "3"
  moisture_exp_alpha: "0.03"
  moisture_exp_send_every: "2"


sensor:
  - platform: adafruit_soil_sensor
    address: ${i2c_address}
    i2c_id: ${i2c_bus}
    temperature:
      id: ${temperature_id}
      name: "${temperature_name}"
      offset: ${temperature_offset}
      gain: ${temperature_gain}
      filters:
        - sliding_window_moving_average:
            window_size: ${temperature_window_size}
            send_every: ${temperature_window_send_every}
            send_first_at: ${temperature_window_send_first_at}      
    moisture:
      id: ${moisture_id}
      name: "${moisture_name}"
      min_value: ${moisture_min_value}
      max_value: ${moisture_max_value}
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: ${moisture_window_size}
            send_every: ${moisture_window_send_every}
            send_first_at: ${moisture_window_send_first_at}
        - exponential_moving_average:
            alpha: ${moisture_exp_alpha}
            send_every: ${moisture_exp_send_every}
    update_interval: ${update_interval}


binary_sensor:
  - platform: adafruit_soil_sensor
    id: ${dry_id}
    name: "${dry_name}"
    sensor_id: ${id_prefix}_moisture
    threshold: ${dry_threshold}
    hysteresis: ${dry_hysteresis}
    internal: false
    icon: mdi:water-percent-alert

