substitutions:
  postfix: ""
  temperature_id: soil_temperature_${postfix}
  temperature_name: "Soil Temperature ${postfix}"
  temperature_offset: "0.0"
  temperature_gain: "1.0"
  temperature_window_size: "5"
  temperature_window_send_every: "5"
  temperature_window_send_first_at: "5"
  moisture_id: soil_moisture_${postfix}
  moisture_name: "Soil Moisture ${postfix}"
  moisture_min_value: "350"
  moisture_max_value: "1015"
  update_interval: 2s
  moisture_window_size: "3"
  moisture_window_send_every: "3"
  moisture_window_send_first_at: "3"
  moisture_exp_alpha: "0.03"
  moisture_exp_send_every: "2"
  i2c_address: "0x36"


sensor:
  - platform: adafruit_soil_sensor
    address: ${i2c_address}
    temperature:
      id: ${temperature_id}
      name: ${temperature_name}
      offset: ${temperature_offset}
      gain: ${temperature_gain}
      filters:
        - sliding_window_moving_average:
            window_size: ${temperature_window_size}
            send_every: ${temperature_window_send_every}
            send_first_at: ${temperature_window_send_first_at}      
    moisture:
      id: ${moisture_id}
      name: ${moisture_name}
      min_value: ${moisture_min_value}
      max_value: ${moisture_max_value}
      accuracy_decimals: 2
      on_raw_value:
        - logger.log:
            format: "Moisture raw value: %.0f"
            args: ["id(${moisture_id}).state"]
      filters:
        - clamp:
            min_value: 0
            max_value: 100
            ignore_out_of_range: true
        - round: 0
        # - sliding_window_moving_average:
        #     window_size: ${moisture_window_size}
        #     send_every: ${moisture_window_send_every}
        #     send_first_at: ${moisture_window_send_first_at}
        - exponential_moving_average:
            alpha: ${moisture_exp_alpha}
            send_every: ${moisture_exp_send_every}
        - round: 0
    update_interval: ${update_interval}

