
substitutions:
  framework: "esp-idf"

defaults:
  connection_slots: "3"
  active_proxy: "false"
  active_tracker: "true"

esp32:
  framework:
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"


bluetooth_proxy:
  active: ${active_proxy}
  connection_slots: ${connection_slots}

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: ${active_tracker}


sensor:
  - platform: ble_rssi
    irk: !secret aarons_watch_irk_only
    name: "Aaron's Watch RSSI"
  - platform: ble_rssi
    irk: !secret thaos_watch_irk_only
    name: "Thao's Watch RSSI"
  - platform: ble_rssi
    irk: !secret paio_irk_only
    name: "Paio RSSI"
  - platform: ble_rssi
    irk: !secret carpaccio_irk_only
    name: "Carpaccio RSSI"
  - platform: ble_rssi
    irk: !secret bacon_irk_only
    name: "Bacon RSSI"
  - platform: ble_rssi
    irk: !secret ham_irk_only
    name: "Ham RSSI"