substitutions:
  bme280_temperature_id: temperature
  bme280_temperature_name: Temperature
  bme280_humidity_id: humidity
  bme280_humidity_name: Humidity
  bme280_pressure_id: pressure
  bme280_pressure_name: Pressure

defaults:
  update_interval: 10s
  i2c_address: "0x77"
  i2c_bus_id: bus_a

sensor:
  - platform: bme280_i2c
    id: bme280_sensor
    i2c_id: ${i2c_bus_id}
    address: ${i2c_address}
    update_interval: ${update_interval}
    temperature:
      id: ${bme280_temperature_id}
      name: ${bme280_temperature_name}
    humidity:
      id: ${bme280_humidity_id}
      name: ${bme280_humidity_name}
    pressure:
      id: ${bme280_pressure_id}
      name: ${bme280_pressure_name}