substitutions:
#  board_type: esp32dev
  i2c_frequency: 800kHz
  i2c_sda_pin: SDA1
  i2c_scl_pin: SCL1
  framework: "arduino"

packages:
  device_base: !include common.yaml


esp32:
  board: ${board_type}
  framework:
    type: ${framework}


i2c:
  - id: bus_a
    sda: 
      number: ${i2c_sda_pin}
    scl: 
      number: ${i2c_scl_pin}
    frequency: ${i2c_frequency}
    scan: true
    setup_priority: 600
