substitutions:
  board_type: adafruit_feather_esp32s2_tft
  i2c_frequency: 800kHz
  i2c_sda_pin: GPIO3
  i2c_scl_pin: GPIO4
  i2c_power_pin: GPIO7
  spi_mosi_pin: GPIO35
  spi_miso_pin: GPIO37
  spi_sck_pin: GPIO36
  neopixel_pin: GPIO33
  neopixel_power_pin: GPIO21


packages:
  device_base: !include esp32.yaml
  wifi: !include wifi.yaml
  neo: !include 
#    file: rmt_led.yaml
    file: neopixel.yaml
    vars:
      neopixel_pin: ${neopixel_pin}
  neo_pwr: !include 
    file: neopixel_power.yaml
    vars:
      neopixel_power_pin: ${neopixel_power_pin}


esphome:
  platformio_options:
    board_build.flash_mode: dio


spi: 
  clk_pin: 
    number: ${spi_sck_pin}
  mosi_pin: 
    number: ${spi_mosi_pin}
  miso_pin: 
    number: ${spi_miso_pin}


switch:
  - platform: gpio
    id: i2c_power
    restore_mode: ALWAYS_ON
    pin: 
      number: ${i2c_power_pin}


status_led:
  pin:
    number: GPIO13
    inverted: false

