substitutions:
  board_type: adafruit_feather_esp32s3
  i2c_frequency: 800kHz
  i2c_sda_pin: GPIO3
  i2c_scl_pin: GPIO4
  i2c_power_pin: GPIO7
  spi_mosi_pin: GPIO35
  spi_miso_pin: GPIO37
  spi_sck_pin: GPIO36
  neopixel_pin: GPIO33
  neopixel_power_pin: GPIO21


packages:
  device_base: !include esp32.yaml
  wifi: !include wifi.yaml
  neo_pwr: !include 
    file: neopixel_power.yaml
    vars:
      neopixel_power_pin: ${neopixel_power_pin}
  neo: !include 
    file: rmt_led.yaml
    vars:
      neopixel_pin: ${neopixel_pin}
      method: esp32_rmt


i2c:
  - id: !extend bus_a
    sda:
      ignore_strapping_warning: true


esp32:
  variant: esp32s3


spi: 
  clk_pin: 
    number: ${spi_sck_pin}
  mosi_pin: 
    number: ${spi_mosi_pin}
  miso_pin: 
    number: ${spi_miso_pin}
#  interface: software


switch:
  - platform: gpio
    id: i2c_power
    restore_mode: ALWAYS_ON
    pin: 
      number: ${i2c_power_pin}

