substitutions:
  board_type: adafruit_feather_esp32s3_tft
  display_id: display_id
  display_model: TTGO TDisplay 135x240
  st7789_cs_pin: GPIO42
  st7789_dc_pin: GPIO40
  st7789_reset_pin: GPIO41
  st7789_backlight_pin: GPIO45
  st7789_ps_pin: GPIO7
  st7789_ps: display_ps
  st7789_rotation: "90"



packages:
  device_base: !include feather_esp32s3.yaml
  display: !include st7789v.yaml


display:
  - id: !extend ${display_id}
    power_supply: ${st7789_ps}  
    backlight_pin:
      number: ${st7789_backlight_pin}
      ignore_strapping_warning: true
    show_test_card: false


power_supply:
  - id: ${st7789_ps}
    pin: 
      number: ${st7789_ps_pin}
    enable_on_boot: true


switch:
  - id: !remove i2c_power


output:
  - id: !extend backlight_output
    pin:
      ignore_strapping_warning: true



