substitutions:
  neopixel_power_pin: NEOPIXEL_POWER
  neopixel_pin: NEOPIXEL

switch:
  - id: neopixel_power
    platform: gpio
    restore_mode: ALWAYS_ON
    pin: 
      number: ${neopixel_power_pin}


light:
 - id: neopixel_led
   platform: neopixelbus
   type: GRB
   variant: WS2812
   pin: 
     number: ${neopixel_pin}
   num_leds: 1
   name: "NeoPixel"
   restore_mode: RESTORE_DEFAULT_OFF
   effects:
    - strobe:
        name: "blink red"
        colors:
          - state: true
            red: 100%
            green: 0
            blue: 0
            brightness: 100%
            duration: 250ms
          - state: true
            red: 0
            green: 0
            blue: 0
            brightness: 0
            duration: 250ms