substitutions:
  board_type: adafruit_qtpy_esp32
  i2c_frequency: 800kHz
  i2c_sda_pin: GPIO22
  i2c_scl_pin: GPIO19
  spi_mosi_pin: GPIO13
  spi_miso_pin: GPIO12
  spi_sck_pin: GPIO14
  neopixel_pin: GPIO5
  neopixel_power_pin: GPIO8

packages:
  device_base: !include esp32.yaml 
  wifi: !include wifi.yaml
  neo_pwr: !include
    file: neopixel_power.yaml
    vars:
      neopixel_power_pin: ${neopixel_power_pin}
      ignore_pin_validation_error: "true"
  neo: !include 
    file: neopixel.yaml
    vars:
      neopixel_pin: ${neopixel_pin}
      ignore_strapping_warning: "true"


spi:
  clk_pin: 
    number: ${spi_sck_pin}
  mosi_pin: 
    number: ${spi_mosi_pin}
  miso_pin: 
    number: ${spi_miso_pin}
    ignore_strapping_warning: true

