defaults:
  neopixel_name: NeoPixel
  neopixel_pin: NEOPIXEL
  neopixel_id: neopixel_led
  num_leds: "1"
  order: GRB
  channel: "0"
  chipset: SK6812
  ignore_pin_validation_error: "false"
  ignore_strapping_warning: "false"

packages:
  effects: !include 
    file: led_effects.yaml
    vars:
      light_id: ${neopixel_id}

light:
  - id: ${neopixel_id}
    platform: esp32_rmt_led_strip
    rgb_order: ${order}
    chipset: ${chipset}
    rmt_channel: ${channel}
    pin: 
      number: ${neopixel_pin}
      ignore_pin_validation_error: ${ignore_pin_validation_error}
      ignore_strapping_warning: ${ignore_strapping_warning}
    num_leds: ${num_leds}
    name: ${neopixel_name}
    restore_mode: RESTORE_DEFAULT_OFF
