substitutions:
  climate_throttle_average: 10s

defaults:
  update_interval: 1s
  temperature_id: temperature
  temperature_name: "Temperature"
  humidity_id: humidity
  humidity_name: "Humidity"
  i2c_address: "0x44"
  i2c_bus_id: bus_a

sensor:
  - platform: sht4x
    id: sht4x_sensor
    i2c_id: ${i2c_bus_id}
    address: ${i2c_address}
    update_interval: ${update_interval}
    heater_max_duty: 0.01
    heater_power: High
    heater_time: Long
    temperature:
      name: ${temperature_name} 
      id: ${temperature_id}
      filters:
        - throttle_average: ${climate_throttle_average}
        - filter_out: nan
        # - exponential_moving_average:
        #     alpha: 0.1
        #     send_every: 1
    humidity:
      name: ${humidity_name}
      id: ${humidity_id}
      filters:
        - throttle_average: ${climate_throttle_average}
        - filter_out: nan
        # - exponential_moving_average:
        #     alpha: 0.1
        #     send_every: 1
