
defaults:
  sensor_id: soil_dry
  led_id: neopixel_led


binary_sensor:
  - id: !extend ${sensor_id}
    on_state:
      if:
        condition:
          binary_sensor.is_on: ${sensor_id}
        then:
          - light.turn_on:
              id: ${led_id}
              effect: "blink red"
        else:
          - light.turn_off: ${led_id}
