substitutions:
  display_id: st7789v_id
  display_model: Custom
  st7789_cs_pin: GPIO14
  st7789_dc_pin: GPIO27
  st7789_reset_pin: GPIO33
  st7789_backlight_pin: GPIO26
  # st7789_width: "172"
  # st7789_height: "320"
  # st7789_offset_height: "34"
  # st7789_offset_width: "0"
  # st7789_rotation: "90"

defaults:
  update_interval: 0.5s


output:
  - platform: ledc
    id: backlight_output
    pin: 
      number: ${st7789_backlight_pin}
      allow_other_uses: true


light:
  - platform: monochromatic
    output: backlight_output
    name: "Backlight"
    restore_mode: ALWAYS_ON
    default_transition_length: 0.1s


display:
  - platform: st7789v
    id: ${display_id}
    model: ${display_model}
    cs_pin: 
      number: ${st7789_cs_pin}
    dc_pin: 
      number: ${st7789_dc_pin}
    reset_pin: 
      number: ${st7789_reset_pin}
    backlight_pin: 
      number: ${st7789_backlight_pin}
      allow_other_uses: true
    height: ${st7789_height}
    width: ${st7789_width}
    offset_height: ${st7789_offset_height}
    offset_width: ${st7789_offset_width}
    rotation: ${st7789_rotation}
    update_interval: ${update_interval}