defaults:
  update_interval: 5s
  i2c_address: "0x10"

sensor:
- platform: veml7700
  address: ${i2c_address}
  update_interval: ${update_interval}
  ambient_light: "Ambient light"
  actual_gain:
    name: "Actual Gain"
