substitutions:
  dns_domain: sf.aberrant.org
  board_type: wesp32
  i2c_scl_pin: GPIO5
  i2c_sda_pin: GPIO33


defaults:
  fqdn: ${hostname}.${dns_domain}

packages:
  device_base: !include esp32.yaml


i2c:
  - id: !extend bus_a
    # sda: 
    #   ignore_strapping_warning: true
    scl:
      ignore_strapping_warning: true
      

ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk:
    pin:
      number: GPIO0
      ignore_strapping_warning: true
    mode: CLK_EXT_IN
  phy_addr: 0
  phy_registers:
    - address: 0x10
      value: 0x1FFA # bit 12 sets clock mode input
      page_id: 0x07

  use_address: ${fqdn}