- platform: template
  fans: 
    peloton_fan:
      friendly_name: "Peloton Fan"
      unique_id: peloton_fan
      value_template: "{{ states('sensor.peloton_fan_plug_power') | float(0) > 1 }}"
      turn_on:
        # action: 
        #   - service: irtrans.send_irtrans_ir_command_vornado
        #     data:
        #       remote: vornado
        #       command: POWER
        #     target: sensor.irtrans_sensor
        action: rest_command.peloton_fan_power_ir
      turn_off:
        action: rest_command.peloton_fan_power_ir
        # action: 
        #   - service: irtrans.send_irtrans_ir_command_vornado
        #     data:
        #       remote: vornado
        #       command: POWER
        #     target: sensor.irtrans_sensor
