substitutions:
  name: bedroom-air-conditioner-plug
  friendly_name: Bedroom Air Conditioner Plug
  hostname: plug-bedroom-air-conditioner
  device_description: "Plug for Bedroom Air Conditioner"
  room: Bedroom
  throttle_average: 1s

packages:
  device_base: !include common/sonoff_s31.yaml


