substitutions:
  name: cat-bed
  friendly_name: Cat Bed
  hostname: plug-cat-bed
  room: Living Room
  device_description: "Cat Bed Smart Plug"
  throttle_average: 10s

packages: 
  device_base: !include common/athom_plug.yaml

wifi:
  use_address: 10.3.3.25

sensor:
  - id: !extend cse7766_sensor
    power:
      filters:
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
