substitutions:
  name: kitchen-air-quality
  friendly_name: Kitchen Air Quality
  room: "Kitchen"
  hostname: air-monitor-kitchen
  device_description: Kitchen Air Monitor and Soil Sensor
  log_level: INFO
  i2c_frequency: 100kHz



packages:
  device_base: !include common/qtpy_esp32s3.yaml
  soil: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x36"
      dry_threshold: "45"
  dry: !include
    file: common/soil_dry_indicator.yaml
    vars:
      sensor_id: soil_dry
  pmsa: !include common/pmsa003i.yaml
  temp: !include common/sht4x.yaml
  dp: !include common/dew_point.yaml
      
logger:
  logs:
    sht4x: INFO
    pmsa003i: INFO
    AQI: INFO
    sensor.filter: INFO

#    adafruit_soil_sensor: INFO