substitutions:
  name: kitchen-fan-plug
  friendly_name: Kitchen Fan Plug
  room: Kitchen
  hostname: plug-kitchen-fan
  device_description: "Kitchen Fan Power Monitor"
  throttle_average: 1s

packages:
  device_base: !include common/sonoff_s31.yaml


