substitutions:
  name: kitchen-air-quality
  friendly_name: Kitchen Air Quality
  room: "Kitchen"
  hostname: air-monitor-kitchen
  device_description: Kitchen Air Monitor and Soil Sensor
  log_level: INFO
  i2c_frequency: 100kHz
  dry_threshold_1: "40"
  moisture_window_size: "3"
  moisture_window_send_every: "3"
  moisture_window_send_first_at: "3"
  soil_moisture_1_id: soil_moisture


packages:
  device_base: !include common/qtpy_esp32.yaml
  dry: !include common/soil_dry_indicator.yaml
  soil: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x36"
  pmsa: !include common/pmsa003i.yaml
  temp: !include common/sht4x.yaml
  dp: !include common/dew_point.yaml
      