substitutions:
  name: living-room-humidifier-plug
  friendly_name: Living Room Humidifier Plug
  hostname: plug-living-room-humidifier
  device_description: "Plug for living room humidifier"
  room: Living Room

packages:
  device_base: !include common/sonoff_s31.yaml


