substitutions:
  name: living-room-ble-proxy
  friendly_name: "Living Room BLE Proxy"
  hostname: ble-proxy-livingroom
  room: "Living Room"
  device_description: "Living Room BLE Proxy for Bermuda"
  log_level: INFO
  framework: "esp-idf"


packages:
  device_base: !include common/olimex_esp32-POE.yaml
  ble: !include common/bluetooth_proxy.yaml