substitutions:
  name: living-room-east-soil-sensor
  friendly_name: Living Room South East Soil Sensor
  room: "Living Room"
  hostname: soil-sensor-livingroom-east
  device_description: South East Soil Sensor
  log_level: INFO
  i2c_frequency: 100kHz
  dry_threshold: "40"
  moisture_window_size: "3"
  moisture_window_send_every: "3"
  moisture_window_send_first_at: "3"
  soil_moisture_1_id: soil_moisture_1
  soil_temperature_1_id: soil_temperature_1
  soil_moisture_2_id: soil_moisture_2
  soil_temperature_2_id: soil_temperature_2
  soil_moisture_3_id: soil_moisture_3
  soil_temperature_3_id: soil_temperature_3


packages:
  device_base: !include common/qtpy_esp32.yaml
  soil1: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x36"
      moisture_id: ${soil_moisture_1_id}
      moisture_name: "Soil Moisture 1"
      temperature_id: ${soil_temperature_1_id}
      temperature_name: "Soil Temperature 1"
  soil2: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x37"
      moisture_id: ${soil_moisture_2_id}
      moisture_name: "Soil Moisture 2"
      temperature_id: ${soil_temperature_2_id}
      temperature_name: "Soil Temperature 2"
  soil3: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x38"
      moisture_id: ${soil_moisture_3_id}
      moisture_name: "Soil Moisture 3"
      temperature_id: ${soil_temperature_3_id}
      temperature_name: "Soil Temperature 3"
      
  dry: !include common/soil_dry_indicator.yaml