substitutions:
  name: living-room-sw-soil-sensor
  friendly_name: Living Room South West Soil Sensor
  room: "Living Room"
  hostname: soil-sensor-livingroom-sw
  device_description: South West Soil Sensor
  log_level: INFO
  i2c_frequency: 100kHz


packages:
  device_base: !include common/qtpy_esp32s3.yaml
  soil1: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x36"
      id_prefix: "plant_1"
      name_prefix: "Plant 1"
  soil2: !include 
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x37"
      id_prefix: "plant_2"
      name_prefix: "Plant 2"
  soil3: !include
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x38"
      id_prefix: "plant_3"
      name_prefix: "Plant 3"
  soil4: !include
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x39"
      id_prefix: "plant_4"
      name_prefix: "Plant 4"
  soil5: !include
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x36"
      i2c_id: bus_b
      id_prefix: "plant_5"
      name_prefix: "Plant 5"
  soil6: !include
    file: common/adafruit_soil_sensor.yaml
    vars:
      i2c_address: "0x37"
      i2c_id: bus_b
      id_prefix: "plant_6"
      name_prefix: "Plant 6"
      dry_threshold: 30
  bin: !include
    file: common/boolean_or.yaml
    vars:
      sensor_id: soil_dry
      sensor_name: "Soil Dry"
      sensor_id_1: plant_1_dry
      sensor_id_2: plant_2_dry
      sensor_id_3: plant_3_dry
      sensor_id_4: plant_4_dry
      sensor_id_5: plant_5_dry
      sensor_id_6: plant_6_dry
  dry: !include
    file: common/soil_dry_indicator.yaml
    var:
      sensor_id: soil_dry
      led_id: neopixel_led


# wifi:
#   use_address: !remove
#   manual_ip:
#     static_ip: 10.3.3.71
#     gateway: 10.3.1.2
#     subnet: 255.255.0.0


i2c:
  - id: bus_b
    sda: 
      number: GPIO7
    scl: 
      number: GPIO6
    frequency: ${i2c_frequency}
    scan: true
    setup_priority: 700
