substitutions:
  name: office-window
  friendly_name: Office Window
  hostname: office-window
  room: Office
  device_description: "Office Window"

packages:
  device_base: !include common/wesp32.yaml
  


switch:
  - platform: gpio
    id: window_close_switch
    restore_mode: ALWAYS_OFF
    pin: GPIO18
    name: "Window Close"
    entity_category: "CONFIG"
    internal: false
    interlock: [window_open_switch]

  - platform: gpio
    id: window_open_switch
    restore_mode: ALWAYS_OFF
    pin: GPIO32
    name: "Window Open"
    entity_category: "CONFIG"
    internal: false
    interlock: [window_close_switch]


output:
  - platform: ledc
    pin: GPIO23
    id: green_button_led
    frequency: 1220Hz

light:
  - platform: monochromatic
    output: green_button_led
    id: button_light
    name: "Button"
    default_transition_length: .2s
    restore_mode: RESTORE_AND_OFF
#    internal: true
    effects:
      - lambda:
          name: Breathing
          update_interval: 1s
          lambda: |-
            static bool state = true;
            static int color = 1;
            auto call = id(button_light).turn_on();
            call.set_transition_length(1000);
            call.set_brightness(1.0);
            if (state)
            {
              call.set_brightness(1.0);
            }
            else
            {
              call.set_brightness(0.20);
            }
            call.perform();
            state = !state;


binary_sensor:
  - platform: gpio
    id: green_button
    icon: mdi:button
    internal: true
    device_class: motion
    pin:
      number: GPIO36
      mode:
        input: true
        pullup: false
    filters:
      - delayed_off: 10ms
    on_press:
      - cover.toggle: office_window
  
  - platform: gpio
    id: window_closed_sensor
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: false
    internal: false
    filters: 
      - delayed_off: 1s
      - delayed_on: 500ms
          
  - platform: gpio
    id: window_open_sensor
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: false
    internal: false
    filters: 
      - delayed_off: 1s

  - platform: template
    id: office_window_closed
    lambda: 'return !id(window_closed_sensor).state;'
    name: Window Closed
    icon: mdi:window
    device_class: window

  - platform: homeassistant
    name: Zigbee Window Sensor
    id: window_open_sensor_2
    entity_id: binary_sensor.office_east_window
    internal: false


cover:
  - platform: endstop
    device_class: window
    id: office_window
    name: "Office Window"

    open_action:
      - switch.turn_on: window_open_switch
      - light.turn_on:
          id: button_light
          effect: Breathing
    open_duration: 32.6s
    open_endstop: window_open_sensor

    close_action:
      - switch.turn_on: window_close_switch
      - light.turn_on:
          id: button_light
          effect: Breathing
    close_duration: 33.4s
    close_endstop: window_closed_sensor
    # on_closed:
    #   - switch.turn_on: window_close_switch
    #   - delay: 0.5s
    #   - switch.turn_off: window_close_switch

    stop_action:
      - switch.turn_off: window_close_switch
      - switch.turn_off: window_open_switch
      - light.turn_off: button_light
    max_duration: 55s