substitutions:
  name: toilet-plug
  friendly_name: Toilet
  hostname: plug-toilet
  room: Bathroom
  device_description: "Bidet Smart Plug"
  throttle_average: 10s

packages: 
  device_base: !include common/athom_plug.yaml

sensor:
  - id: !extend cse7766_sensor
    power:
      filters:
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2