homeassistant:
  enabled: true
serial:
  port: tcp://10.3.1.58:6638
  baudrate: 460800
  disable_led: false
  adapter: zstack
frontend:
  enabled: true
  port: 8099
mqtt:
  server: '!secret.yaml mqtt_server'
  user: '!secret.yaml mqtt_user'
  password: '!secret.yaml mqtt_password'
  base_topic: zigbee2mqtt
  client_id: zigbee2mqtt
  keepalive: 60
  version: 5
advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
  channel: 25
  transmit_power: 20
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  last_seen: disable
  elapsed: false
  output: json
  log_level: info
  network_key:
    - 164
    - 162
    - 94
    - 116
    - 150
    - 49
    - 93
    - 36
    - 18
    - 220
    - 235
    - 115
    - 165
    - 105
    - 250
    - 171
  pan_id: 48879
  ext_pan_id:
    - 65
    - 98
    - 101
    - 114
    - 114
    - 97
    - 110
    - 116
availability:
  enabled: true
  active:
    timeout: 10
  passive:
    timeout: 1500
devices:
  '0x0017880108e2d93f':
    friendly_name: Piano Light
  '0x00158d0009df96a1':
    friendly_name: Office East Window
    homeassistant:
      name: Office East Window
    optimistic: true
  '0x001788010b39e879':
    friendly_name: Living Room Closet Light
  '0x00158d0008e1ba9f':
    friendly_name: Printer Plug
  '0x0017880108e2d3ba':
    friendly_name: Office Ceiling 3
  '0x0017880109107ed2':
    friendly_name: Office Desk Lights
  '0x00178801091086eb':
    friendly_name: Office Bench Lights
  '0x00158d00093e743c':
    friendly_name: Office String Lights
  '0x000d6f0005856a4c':
    friendly_name: Living Room Standing Fan
  '0xb0ce1814036c3465':
    friendly_name: Living Room Couch Plug
  '0x001788010b6dd5fe':
    friendly_name: Hallway Ceiling 1
  '0x001788010b6dd864':
    friendly_name: Hallway Ceiling 2
  '0x54ef441000617a38':
    friendly_name: Bathroom Light
  '0xb0ce1814036c54d6':
    friendly_name: Refrigerator
  '0x00158d0009ee05b4':
    friendly_name: Living Room South Window
  '0x00158d0009ee06d8':
    friendly_name: Living Room North Window
  '0x00158d0009ee040d':
    friendly_name: Living Room South East Window
  '0x00158d0009df4175':
    friendly_name: Front Door
  '0x00178801042a79be':
    friendly_name: Bedside Lamp Right
    description: Poodle lamp
  '0x0017880103eeb09e':
    friendly_name: Bedroom Ceiling 1
  '0x00178801039d730e':
    friendly_name: Bedroom Ceiling 2
  '0x00178801063878cb':
    friendly_name: Office Ceiling 2
  '0x001788010b6dd9a9':
    friendly_name: Kitchen Ceiling 1-1
  '0x0017880106d9db2d':
    friendly_name: Kitchen Ceiling 1-2
  '0x001788010944a507':
    friendly_name: Kitchen Counter East
  '0x0017880109449a57':
    friendly_name: Kitchen Counter West
  '0x00158d00093e707d':
    friendly_name: Bedroom Purifier Plug
  '0x00158d0009ee05bf':
    friendly_name: Bedroom South Window
  '0x00158d0009df4042':
    friendly_name: Bedroom North Window
  '0x001788010d67b5d0':
    friendly_name: Laundry Room Light
  '0x00158d0009ee038b':
    friendly_name: Bedroom Closet Window Sensor
  '0xf0d1b80000077af5':
    friendly_name: Living Room South Grow Light
  '0x001788010dab64c2':
    friendly_name: Front Entry Light
  '0x001788010dab6473':
    friendly_name: Kitchen Ceiling 1-3
  '0x001788010dab6a45':
    friendly_name: Kitchen Ceiling 2-1
  '0xf0d1b80000077a77':
    friendly_name: Living Room North Grow Light
  '0x7cb03eaa00a2651e':
    friendly_name: Cat Bed
  '0x001788010dbfbed2':
    friendly_name: Kitchen Ceiling 2-3
  '0x001788010dbfeaed':
    friendly_name: Bedside Lamp Left
    description: Cat lamp
  '0x001788010dbfa658':
    friendly_name: Kitchen Ceiling 2-2
  '0x001788010dbfebcb':
    friendly_name: Hallway Ceiling 3
  '0x001788010dbfec5c':
    friendly_name: Office Ceiling 1
device_options:
  legacy: false
groups:
  '1':
    friendly_name: Office Ceiling Zigbee Group
  '2':
    friendly_name: Office Lights Zigbee Group
  '3':
    friendly_name: Hallway Ceiling Zigbee Group
  '4':
    friendly_name: Bedroom Ceiling Zigbee Group
  '5':
    friendly_name: Bedroom Lights Zigbee Group
  '6':
    friendly_name: Hallway Lights Zigbee Group
  '7':
    friendly_name: All Lights Zigbee Group
  '8':
    friendly_name: Kitchen Ceiling Zigbee Group
  '9':
    friendly_name: Kitchen Counters Zigbee Group
  '10':
    friendly_name: Kitchen Lights Zigbee Group
  '11':
    friendly_name: Grow Lights
  '12':
    friendly_name: Bedroom Lamps
ota:
  disable_automatic_update_check: true
version: 4
